// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicMatch.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicMatch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529184438_RefatoracaoAgenda")]
    partial class RefatoracaoAgenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicMatch.Domain.Entities.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtistaId1")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseCacheHora")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<bool>("EquipamentoProprio")
                        .HasColumnType("boolean");

                    b.Property<string>("FormatoShow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HorarioFinal")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioInicial")
                        .HasColumnType("interval");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("ArtistaId1");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseCacheHoraAte")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ContratanteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EquipamentoProprio")
                        .HasColumnType("boolean");

                    b.Property<string>("FormatoShow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("interval");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("RaioKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Artista", b =>
                {
                    b.HasBaseType("MusicMatch.Domain.Entities.Usuario");

                    b.ToTable("Artistas", (string)null);
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Contratante", b =>
                {
                    b.HasBaseType("MusicMatch.Domain.Entities.Usuario");

                    b.ToTable("Contratantes", (string)null);
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Agenda", b =>
                {
                    b.HasOne("MusicMatch.Domain.Entities.Artista", null)
                        .WithMany("Agendas")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicMatch.Domain.Entities.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaId1");

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Evento", b =>
                {
                    b.HasOne("MusicMatch.Domain.Entities.Contratante", "Contratante")
                        .WithMany("Eventos")
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratante");
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Artista", b =>
                {
                    b.HasOne("MusicMatch.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("MusicMatch.Domain.Entities.Artista", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Contratante", b =>
                {
                    b.HasOne("MusicMatch.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("MusicMatch.Domain.Entities.Contratante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Artista", b =>
                {
                    b.Navigation("Agendas");
                });

            modelBuilder.Entity("MusicMatch.Domain.Entities.Contratante", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
